#cloud-config
timezone: Asia/Tokyo
package_update: true
packages:
  - git
  - httpd
  - mariadb-server
  - mariadb
  - php
  - php-mysqlnd
runcmd:
  - systemctl start httpd.service
  - systemctl enable httpd.service
  - systemctl start mariadb
  - systemctl enable mariadb.service
  - git clone https://github.com/takasou777/php-test.git
  - cp /root/php-test/* /var/www/html
  - chmod 744 /var/www/html/*
  - sudo rpm --import https://repo.logdna.com/logdna.gpg
  - echo -e "[logdna]\nname=LogDNA packages\nbaseurl=https://repo.logdna.com/el6/\nenabled=1\ngpgcheck=1\ngpgkey=https://repo.logdna.com/logdna.gpg" | sudo tee /etc/yum.repos.d/logdna.repo
  - sudo yum -y install logdna-agent
  - logdna-agent -k ${logdna_ingestion_key}
  - systemctl start logdna-agent
  - systemctl enable logdna-agent
  - curl -sL https://ibm.biz/install-sysdig-agent | sudo bash -s -- -a ${monitoring_access_key} -c ingest.jp-tok.monitoring.cloud.ibm.com --collector_port 6443 --secure true -ac "sysdig_capture_enabled":" false"
